server:
  port: 4000
  compression:
    enabled: true # 开启Gzip
    mime-types: application/json,application/xml,text/html,text/xml,text/plain # 数据类型
    min-response-size: 1 # 开启压缩最小数据字节数默认2048个‘字节’

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
  devtools:
    restart:
      enabled: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  mail:
    username: admin@lete114.top # 邮件提醒的 邮箱 / 用户
    password: xxxxxxxxx # 邮件的密码
    host: smtp.exmail.qq.com # 邮件服务器
    properties:
      "mail.smtp.ssl.enable": true

# mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: top.lete114.entity

# 配置分页插件pagehelper
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true



